name: flutter_offline
description: A tidy utility to handle offline/online connectivity like a Boss.
version: 2.0.0
homepage: https://github.com/jogboms/flutter_offline

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: any
  wifi_info_flutter: any

dev_dependencies:
  pedantic: any

dependency_overrides:
  connectivity:
    git:
      url: "https://github.com/vickyleu/simple_connectivity.git"
